require: rubocop-rails

Style/StringLiterals:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 150

GlobalVars:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 15